= ez-plugin

For when you need a plugin system.

== Dependancy
```clojure
[ez-plugin "0.1.1"]
```

== Rationale

You wish to build a system and allow for third parties to extend the system with
new functionality. ez-plugin allows for defining hooks to be loaded and executed
by the system in any JAR file currently loaded on the classpath.

Combine with https://github.com/cemerick/pomegranate[pomegranate] for
downloading JAR files at runtime.

== Usage

. Library (loaded as a JAR) to be loaded as a plugin
. An EDN file in the file path of the JAR (for example in resources)
.. The EDN file can be named anything
.. If placed in the root of resources, the path is the file name
. You run the following code

```clojure
(require '[ez-plugin.core :as plugin])
(plugin/load-plugins "plugin.edn" {})
(plugin/load-plugins
  ;; look for this file in all the JAR files currently loaded
  "awesome/system/plugin.edn"
  ;; send in our context map
  {:version 1 :context-map? true}
  ;; an optional opt map
  {;; the EDN file should use this key for holding the hooks. defaults
   ;; to :hooks
   :hooks-key :foobar/hooks
   ;; should any exceptions bubble up or silently supressed
   ;; defaults to false
   :bubble? true}})
```

The EDN file must look like this. The hooks specified as a vector with the fully qualifed path to the functions you wish to call. The context map is passed as an argument to the function.

```clojure
{:hooks [ez-plugin-test1.core/hook]}
```

See in the code base for examples.

== Testing &amp; development

In order to develop the library and to run the tests,
the two test libraries must first be installed.

== License

Copyright © 2019 Emil Bengtsson

___

Coram Deo
